import { ENVIRONMENT_CONSTANTS } from './environmentConstants';
import GLOBAL_CONSTANTS from './globalConstants';

const { IP_DOMAIN, PROTOCOL, PORT } = ENVIRONMENT_CONSTANTS;

const PSP_DOMAIN = 'https://client.ypc.biz:';

const PORTS = {
  ALPHA: PORT.YPC,
  PSP: window.location.host.indexOf('localhost') > -1 ? '8091' : '1443',
  BLACK_BOX: `${PORT.ORION}020`,
}; // PORTS
const API = {
  API: '/api',
  AGENDA: '/api/agenda',
  CAMPAIGNS_APLICATIONS: '/api/campaignApplications',
  CAMPAIGNS: '/api/campaign',
  CATALOGS: '/api/catalogs',
  CATALOGS_CONFIG: '/api/CatalogsConfig',
  CALL: '/api/call',
  COMMUNICATIONS: '/api/communications',
  EMAIL: '/api/email',
  EMAIL_SERVICE: '/api/emailService',
  NOTIFICATIONS: '/api/notifications',
  COMPLIANCE: '/api/compliance',
  DOCUMENTS: '/api/documents',
  CRM: '/api/crm',
  LEAD: '/api/lead',
  FILE_PSYCHOMETRIC: '/api/filePsychometric',
  CONTRATATION: '/api/contratation',
  HIRING: '/api/hiring',
  TRAINING: '/api/training',
  INDICATORS: '/api/indicators',
  REPORTS: '/api/reports',
  HR_EMPLOYEE: '/api/hrEmployee',
  HR_HUMAN_RESOURCES: '/api/humanResources',
  HR_SYSTEM_USER: '/api/hrSystemUser',
  HR_OFFICE_ADMINISTRATOR: '/api/officeAdministration',
  LOGIN: '/api/login',
  RECRUITMENT: '/api/recruitment',
  RECRUITMENT_AGENDA: '/api/recruitmentAgenda',
  COURSES: '/api/courses',
  RECRUITMENT_FILE: '/api/recruitmentFile',
  REPOSITORY: '/api/repository',
  REPOSITORY_NODE: '/api/repository',
  CONCESSION: '/api/concession',
  MENU: '/api/menu',
  SYSTEM_CONFIGURATION: '/api/systemConfigurations',
  SALES: '/api/sales',
  BLACK_BOX: '/api/blackBox',
  BLACK_BOX_CATALOGS: '/api/catalogsBlackBox',
  RETAIL: '/api/retail',
  PAY_TO_GO: '/api/PayToGo',
  REPORTS_BLACKBOX: '/api/ReportsBlackBox',
  ALPHA: '/api/client',
  ALPHA_REPOSITORY: '/api/clientRepository',
  ALPHA_CATALOGS: '/api/catalogsClient',
};

const HEADER = {
  // Authorization:      `Bearer ${window.sessionStorage.token}`,
  // Authorization:       'Bearer '+"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWFuYWdlclJIMDAxIiwiaWRDbGllbnRBcHAiOiIyIiwibW9iaWxlSWROdW1iZXIiOiIwIiwiaWRFbXBsb3llZSI6ImMyYzE2Y2VkLTE1MzEtZTcxMS04MGNjLTAwMTU1ZDAxOTgwMCIsImlkVXNlciI6ImQxNDUxNzM3LTUyMzAtZTcxMS04MGNjLTAwMTU1ZDAxOTgwMCIsImlkTGVhZCI6IiIsImlkUm9sZSI6IjgiLCJtaW5TZXNzaW9uVGltZSI6IjYwIiwiaWRQYXNzd29yZFJlcXVlc3QiOiIiLCJqdGkiOiI3OWY2NGIwMS1mODZiLTQ2MDUtYWZkYi0wZTJjYzZkNTFmNzAiLCJpYXQiOjE1MDg0MjM5MzMsIm5iZiI6MTUwODQyMzMzMiwiZXhwIjoxNTA4NDU2MzMyLCJpc3MiOiJPcmlvblN5c3RlbVRva2VuIiwiYXVkIjoiaHR0cDovLzAuMC4wLjA6NTAwMC8ifQ.0RF5Jov5GN09qkm5vNii0r5Jmg-tvr6o1zhG_GGf9Kw",
  'Content-Type': 'application/json',
}; // HEADER
const HEADER_FORM_DATA = {
  // Authorization:      `Bearer ${window.sessionStorage.token}`,
  // Authorization:       'Bearer '+"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWFuYWdlclJIMDAxIiwiaWRDbGllbnRBcHAiOiIyIiwibW9iaWxlSWROdW1iZXIiOiIwIiwiaWRFbXBsb3llZSI6ImMyYzE2Y2VkLTE1MzEtZTcxMS04MGNjLTAwMTU1ZDAxOTgwMCIsImlkVXNlciI6ImQxNDUxNzM3LTUyMzAtZTcxMS04MGNjLTAwMTU1ZDAxOTgwMCIsImlkTGVhZCI6IiIsImlkUm9sZSI6IjgiLCJtaW5TZXNzaW9uVGltZSI6IjYwIiwiaWRQYXNzd29yZFJlcXVlc3QiOiIiLCJqdGkiOiI3OWY2NGIwMS1mODZiLTQ2MDUtYWZkYi0wZTJjYzZkNTFmNzAiLCJpYXQiOjE1MDg0MjM5MzMsIm5iZiI6MTUwODQyMzMzMiwiZXhwIjoxNTA4NDU2MzMyLCJpc3MiOiJPcmlvblN5c3RlbVRva2VuIiwiYXVkIjoiaHR0cDovLzAuMC4wLjA6NTAwMC8ifQ.0RF5Jov5GN09qkm5vNii0r5Jmg-tvr6o1zhG_GGf9Kw",
  'Content-Type': 'multipart/form-data',
}; // HEADER_FORM_DATA

const API_CONSTANTS = {
  IP_DOMAIN,
  PROTOCOL,
  DOMAIN: `${PROTOCOL.ORION}://${IP_DOMAIN.ORION}:`,
  API,
  Authorization: 'Bearer ',
  AGENDA: {
    POST_SCHEDULLE_CALL: `${PORTS.AGENDA + API.AGENDA}/scheduledCall`,
  }, // AGENDA
  CAMPAIGNS: {}, // CAMPAIGNS
  COMMUNICATIONS: {
    POST_SEND_EMAIL: `${PORTS.COMMUNICATIONS}/api/email/addEMailSent`,
    POST_PREVIEW_HTML_EMAIL_TEMPLATE: `${PORTS.COMMUNICATIONS}/api/email/previewSalesEmail`,
    POST_GET_EMAIL_SENT_INFO: `${PORTS.COMMUNICATIONS +
      API.EMAIL}/emailSentInfo`,
    POST_PREVIEW_HTML_EMAIL_TEMPLATE_RH: `${PORTS.COMMUNICATIONS +
      API.EMAIL}/candidate/previewEmail`,
    POST_EMAIL_REQUEST_EMPLOYEE_CONFIG: `${PORTS.COMMUNICATIONS +
      API.EMAIL}/emailTemplate/request/employeeConfig`,
    POST_GET_REQUEST_EMPLOYEE_CONFIG: `${PORTS.COMMUNICATIONS +
      API.EMAIL}/emailSent/request/employee/configuration`,
    GET_EMPLOYEE_CONFIG_INFO: `${PORTS.COMMUNICATIONS +
      API.EMAIL}/emailSent/employee/configuration/information`,
    POST_SEND_EMAIL_EMPLOYEE_CONFIGURATION: `${PORTS.COMMUNICATIONS +
      API.EMAIL}/sendEmail/employee/configuration`,
    POST_GET_EMAIL_SENT_CONFIG_INFO: `${PORTS.COMMUNICATIONS +
      API.EMAIL}/emailSent/employee/config/info`,
  }, // COMMUNICATIONS
  COMPLIANCE: {}, // COMPLIANCE
  CRM: {
    GET_LEAD_CONTACT_STATUS_REPORT: `${PORTS.CRM +
      API.LEAD}/leadContactStatusReport`,
    GET_SEARCH_LEAD: `${PORTS.CRM + API.LEAD}/searchLead`,
    POST_SALES_STATS: `${PORTS.CRM + API.LEAD}/salesStats`,
    POST_GET_LEAD_COINCIDENCES: `${PORTS.CRM + API.LEAD}/leadCoincidences`,
    GET_LEAD_ASSIGNMENT_BY_ID_ASSIGNMENT_TYPE: `${PORTS.CRM +
      API.LEAD}/leadAssignment/byIdAssignmentType/`,
    GET_LEAD_ASSIGNMENT_SUPERVISOR: `${PORTS.CRM +
      API.LEAD}/leadAssignment/byIdAssignmentType/supervisor/`,
    GET_LEAD_ASSIGNMENT_WORKTEAM: `${PORTS.CRM +
      API.LEAD}/leadAssignment/byIdAssignmentType/workTeam/`,
    POST_LEAD_ASSIGNMENT_BULLK_ASSIGN: `${PORTS.CRM +
      API.LEAD}/leadAssignment/bulkAssignedLeadQuantity`,
    GET_LEAD_PROPERTIES: `${PORTS.CRM + API.LEAD}/leadProperty/byIdLead/`,
    POST_LEAD_PROPERTIES: `${PORTS.CRM + API.LEAD}/leadProperty`,
    UPDATE_LEAD_PROPERTIES: `${PORTS.CRM + API.LEAD}/leadProperty/`,
    UPDATE_LEAD_ANSWER_AVOCATION: `${PORTS.CRM +
      API.LEAD}/leadProfiling/answer/LeadAvocationCategory`,
    POST_BULK_ASSIGN_LEAD: `${PORTS.CRM +
      API.LEAD}/leadAssignment/bulkAssignLead`,
    POST_LEAD_PHONE_NUMBERS: `${PORTS.CRM + API.LEAD}/leadPhoneNumber`,
    UPDATE_LEAD_PHONE_NUMBERS: `${PORTS.CRM + API.LEAD}/leadPhoneNumber`,
    POST_LEAD_EMAILS_ADDRESS: `${PORTS.CRM + API.LEAD}/leadEmailAddress`,
    UPDATE_LEAD_EMAIL_ADDRESS: `${PORTS.CRM + API.LEAD}/leadEmailAddress`,
    UPDATE_LEAD_ANSWER_CREDIT_CARD: `${PORTS.CRM +
      API.LEAD}/leadProfiling/answer/LeadCreditCard`,
    POST_LEAD_INFORMATION: `${PORTS.CRM + API.LEAD}/`,
    GET_LEAD_INFO_BY_ID_LEAD: PORTS.CRM + API.LEAD,
    GET_LEAD_PHONE_NUMBERS_BY_ID_LEAD: `${PORTS.CRM +
      API.LEAD}/leadPhoneNumber/byIdLead/`,
    GET_LEAD_EMAIL_ADDRESS_BY_ID_LEAD: `${PORTS.CRM +
      API.LEAD}/leadEmailAddress/byIdLead/`,
  }, // CRM
  FILE_PSYCHOMETRIC: {
    POST_APPOINMENT_HIRING: `${PORTS.FILE_PSYCHOMETRIC +
      API.HIRING}/appointmentHiring/schedule`,
    POST_GET_APPOINTMENT_HIRING: `${PORTS.FILE_PSYCHOMETRIC +
      API.HIRING}/appointmentHiring/`,
    PUT_APPOINTMENT_HIRING: `${PORTS.FILE_PSYCHOMETRIC +
      API.HIRING}/appointmentHiring/`,
  }, // FILE_PSYCHOMETRIC
  HUMAN_RESOURCES: {
    AVAILABLE_VACATIONS_DAYS: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/vacationDays/available`,
    ADD_REQUEST: `${PORTS.HUMAN_RESOURCES + API.HR_HUMAN_RESOURCES}/request`,
    USER_PROFILE: `${PORTS.HUMAN_RESOURCES + API.HR_SYSTEM_USER}/userProfile/`,
    POST_EXCEL_PARAMETERS_ENCRIPT: `${PORTS.HUMAN_RESOURCES +
      API.REPORTS}/excel/parameters/encript`,
    GET_POST_INDICATORS_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.INDICATORS}/recruitment`,
    GET_EMAILS_ADDRESS_BY_ID_EMPLOYEE: `${PORTS.HUMAN_RESOURCES +
      API.HR_EMPLOYEE}/employeeEmailAddress/byIdEmployee/`,
    POST_GET_PROSPECTS_PER_PROCESS: `${PORTS.HUMAN_RESOURCES +
      API.INDICATORS}/prospectsPerProcess`,
    GET_OFFICE_ADMINISTARTOR_EMPLOYER_SELECTED: `${PORTS.HUMAN_RESOURCES +
      API.HR_OFFICE_ADMINISTRATOR}/employee/selected/`,
    PUT_OFFICE_ADMINISTRATOR_EMPLOYER: `${PORTS.HUMAN_RESOURCES +
      API.HR_OFFICE_ADMINISTRATOR}/employer/`,
    GET_OFFICE_ADMINISTRATOR_EMPLOYEE_SHOW_NAME_BY_ID_EMPLOYE: `${PORTS.HUMAN_RESOURCES +
      API.HR_OFFICE_ADMINISTRATOR}/employee/showName/byIdEmployee/`,
    GET_OFFICE_ADMINISTRATOR_VACANCY_ORGANIZATION_CHART_BY_ID_DEPARTMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_OFFICE_ADMINISTRATOR}/vacancy/organizationChart/byIdDepartment/`,
    GET_DEPARTMENT_PROSPECTS_BY_ID_COMPANY: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/department/prospects/byIdCompany/`,
    PUT_INTERVIEW_KEEP_GOING: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/tinterviewKeepGoing/`,
    POST_GET_PROSPECT_BATCH_RAW_INFO_BY_ID_CANDIDATE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/prospectBatch/rawInfo/byIdCandidate`,
    PUT_INTERVIEW_DISCARDED: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/discardCandidate/`,
    PUT_T_INTERVIEW_DISCARDED: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/tinterviewDiscarded/`,
    POST_REPORT_INDICATOR: `${PORTS.HUMAN_RESOURCES +
      API.INDICATORS}/reportIndicators`,

    GET_DASHBORAD_CHART_BY_ID_CHART: `${PORTS.HUMAN_RESOURCES +
      API.HR_SYSTEM_USER}/chart`,

    POST_INDUCTION_COURSE_CLOSE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionCourse/CloseInductionCourse`,
    GET_VACANCY_RECRUITMENT_STATS: `${PORTS.HUMAN_RESOURCES +
      API.HR_OFFICE_ADMINISTRATOR}/vancancy/recruitment/stats/`,
    PUT_INTERVIEW_WRONG_INFO: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/tinterviewWrongInfo/`,
    PUT_INTERVIEW_NO_ANSWER: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/tinterviewNoAnswer/`,
    PUT_INTERVIEW_ANSWER: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/tinterviewAnswer/`,
    GET_INTERVIEW_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/interview/byIdRecruitment/`,
    PUT_CANDIDATE_IMAGE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitmentDocument/candidateImage/`,
    PUT_DISCARD_CANDIDATE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/discardCandidate/`,
    GET_REJECTION_REASON_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/rejectionReason/byIdRecruitment/`,
    PUT_INTERVIEW_TRUNCATE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/tinterviewTruncate/`,
    POST_RECRUITMENT_DOCUMENT_ATTACH_CANDIDATE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitmentDocument/attach/candidateDocument`,
    GET_INTERVIEW_HISTORY_TELEPHONE_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/interview/HistoryTelephone/byIdRecruitment/`,
    GET_EMPLOYEE_SEARCH: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/search/`,
    POST_F2FINTERVIEW_IN_PROGRESS: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/F2FInterviewInProgress/`,

    GET_INTERVIEW_LAST_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/interview/last/byIdRecruitment/`,
    GET_INTERVIEW_HISTORY_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/interview/history/byIdRecruitment/`,
    GET_INTERVIEW_GRADE_RESULT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/interviewGradeResult/`,
    PUT_INTERVIEW_GRADE_RESULT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/interviewGradeResult/`,
    POST_GET_PHASE_PYSCHO_RESULT_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitmentPhaseResult/psychoResult/byIdRecruitment`,
    POST_RECRUITMENT_PHASE_RESULT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitmentPhaseResult/psychoResult`,
    POST_GET_PSYCHO_TEST_RESULTS_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitmentPsychometric/PsychoTestResults/byIdRecruitment`,
    POST_PSYCHOMETRIC_ANSWER: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/PsychoAnswer`,
    POST_PSYCHOMETRIC_DOCUMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/psychometricDocument`,
    PUT_PSYCO_TEST_DEAD_LINE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/psycoTestDeadline/byIdRecruitment/`,
    GET_PSYCO_TEST_DEAD_LINE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/psycoTestDeadline/`,
    POST_GET_EMPLOYEE_CONFIG_SEARCH: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/search/config`,
    GET_INDUCTION_COURSE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionCourse/`,

    PUT_L_INTERVIEW_IN_PROGRESS: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/LInterviewInProgress/`,
    PUT_L_INTERVIEW_CONCLUDED: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/LInterviewConcluded/`,
    PUT_L_INTERVIEW_DISCARDED: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/LInterviewDiscarded/`,
    PUT_L_INTERVIEW_KEEP_GOING: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/LInterviewKeepGoing/`,

    POST_GET_EMPLOYEE_SEARCH_LEADER_INTERVIEWER: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/search/liderInterviewer`,
    POST_GET_EMPLOYEE_SEARCH_INTERVIEWER: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/search/interviewer`,

    GET_HISTORY_LEADER_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/interview/historyLider/byIdRecruitment/`,
    GET_CHECKED_TOPIC_BY_ID_INDUCTION_COURSE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/CheckedTopic/byIdInductionCourse/`,
    PUT_INDUCTION_COURSE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionCourse/`,
    POST_GET_INDUCTION_COURSE_ATTENDANTS_DISCARDED_FROM_COURSE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionCourseAttendants/DiscardedFromCourse`,
    POST_ATTENDANT_COMMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/attendantComment`,
    POST_ATTENDANCE_IN_COURSE_CALL_THE_ROLL: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/attendanceInCourse/callTheRoll`,

    POST_GET_INDUCTION_COURSE_COINCIDENCES: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionCourse/coincidences`,

    PUT_CHECKED_TOPIC: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/CheckedTopic/`,
    PUT_BULK_DISCARD_CANDIDATE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/bulkDiscardCandidate`,
    POST_INDUCTION_COURSE_DISCARDED: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionCourseDiscarded`,
    POST_INTERVIEW_HIRING_COINCIDENCES: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/interview/hiringCoincidences`,

    POST_INDUCTION_COURSE_SCHEDULE_COURSE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionCourse/scheduleCourse`,

    POST_CANDIDATE_HISTORY_HIRING: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/candidate/history`,
    PUT_CONTRACT_SIGN_DISCARDED: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/ContractSignDiscarded/`,
    GET_EMPLOYEE_HIRING: `${PORTS.HUMAN_RESOURCES + API.HR_EMPLOYEE}/hiring/`,
    POST_GET_COMISSION_PLAN_ALL: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/commisionPlan/all/comboBox`,
    GET_RECRUITMENT_INFORMATION_BY_ID: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitment/information/byId/`,
    GET_EMPLOYEE_INMEDIATE_ALL: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/immediate/all/comboBox/`,
    POST_RECRUITMENT_DOCUMENT_ALL_BY_ID_EMPLOYEE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/recruitmentDocument/document/all/byIdEmployee`,

    POST_GET_TRAINING_EMPLOYEE_SEARCH_SUPERVISOR: `${PORTS.HUMAN_RESOURCES +
      API.TRAINING}/employee/SearchSupervisor`,
    GET_INDUCTION_TEST_BY_ID_RECRUITMENT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionTest/byIdRecruitment/`,
    PUT_INDUCTION_COURSE_APPROVE_CANDIDATE_COURSE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/inductionCourseAttendants/approveCandidate/course/`,

    POST_REPORTS_EXCEL_PARAMETERS_ENCRIPT: `${PORTS.HUMAN_RESOURCES +
      API.REPORTS}/excel/parameters/encript`,
    LINK_REPORTS_EXCEL: `${PORTS.HUMAN_RESOURCES + API.REPORTS}/excel`,

    POST_EMPLOYEE_INCIDENCE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employeeIncidence`,
    GET_EMPLOYEE_INCIDENCE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employeeIncidence/`,
    PUT_EMPLOYEE_INCIDENCE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employeeIncidence/`,

    PUT_EMPLOYEE_INCIDENCE_JUSTIFY: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employeeIncidence/justify/`,
    POST_GET_EMPLOYEE_STATS: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/stats`,
    POST_GET_EMPLOYEE_EX_COINCIDENCES: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/ex/coincidences`,
    POST_GET_EMPLOYEE_COINCIDENCES: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/coincidences`,

    POST_VACANCY_JOB_POSITION_CHECK_AVAIBLE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/vacancyJobPosition/checkAvailable`,
    POST_HR_EMPLOYEE_HIRING: `${PORTS.HUMAN_RESOURCES +
      API.HR_EMPLOYEE}/hiring`,
    PUT_ACTIVATE_EMPLOYEE: `${PORTS.HUMAN_RESOURCES +
      API.HR_EMPLOYEE}/activateEmployee/`,
    POST_EMPLOYEE_WORKING_HOURS: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employeeWorkingHours`,
    POST_INCIDENCE_DOCUMENT_ATTACH: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/incidenceDocument/attach`,
    GET_INCIDENCE_DOCUMENT_ALL: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/incidenceDocument/all/`,
    GET_INCIDENCE_STAT: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/incidenceStat/`,
    POST_GET_INCIDENCE_COINCIDENCES: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/incidenceDocument/coincidences`,
    POST_GET_PAY_ROLL_BY_ID_EMPLOYEE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employeePayroll/byIdEmployee`,
    POST_GET_BANK_DATA_BY_ID_EMPLOYEE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employeeBankData/byIdEmployee`,
    PUT_EMPLOYEE_BANK_DATA: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employeeBankData/`,
    POST_HIRING_ADD_DISSMISS: `${PORTS.HUMAN_RESOURCES +
      API.HR_EMPLOYEE}/hiring/addDissmiss`,
    GET_REQUEST_STATS: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/request/stats/`,
    GET_EMPLOYEE_INFO_BY_ID: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/information/byId/`,
    GET_VACATIONS_REQ_COINCIDENCES: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/request/vacation/coincidences`,
    PUT_JUSTIFY_REQUEST: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/request/justify/`,
    PUT_REJECT_REQUEST: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/request/reject/`,
    PUT_APPROVE_REQUEST: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/request/approve/`,
    GET_COMPLETION_REQ_COINCIDENCES: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/employee/completion/coincidences`,
    GET_REQ_BY_ID: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/request/byId/`,
    PUT_HR_EMPLOYEE_HIRING: `${PORTS.HUMAN_RESOURCES +
      API.HR_EMPLOYEE}/hiring/`,
    POST_HIRE_CANDIDATE: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/hiringCandidate`,

    POST_REQUEST_DOCUMENT_ATTACH: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/requestDocument/attach/`,
    GET_REQUEST_BY_ID: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/request/byId/`,
    GET_REQUEST_DOCUMENT_ALL: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/requestDocument/all/`,
    PUT_REQUEST: `${PORTS.HUMAN_RESOURCES + API.HR_HUMAN_RESOURCES}/request/`,

    POST_GET_REQUEST_COINCIDENCES: `${PORTS.HUMAN_RESOURCES +
      API.HR_HUMAN_RESOURCES}/request/coincidences`,

    GET_REPORTS_EXCEL: `${PORTS.HUMAN_RESOURCES + API.REPORTS}/excel?v=`,
  }, // HUMAN_RESOURCES
  PROFILING: {
    LEAD_PROFILING_BY_ID_LEAD: `${PORTS.CRM}/api/lead/leadProfiling/`,
    ADD_LEAD_PROFILING: `${PORTS.CRM}/api/lead/leadProfiling`,
    GET_LEAD_SUMMARY: `${PORTS.CRM}/api/lead/leadProfiling/ProfilingSummary/byIdLead/`,
    GET_CREDIT_CARD_LIST: `${PORTS.CRM}/api/lead/leadCreditCard/`,
    UPDATE_LEAD_CREDIT_CARD: `${PORTS.CRM}/api/lead/leadCreditCard`,
    ADD_LEAD_CREDIT_CARD: `${PORTS.CRM}/api/lead/leadCreditCard`,
    ADD_SUBCATEGORY_ANSWER: `${PORTS.CRM}/api/lead/leadAvocation`,
    GET_SUBCATEGORY_ANSWER: `${PORTS.CRM}/api/lead/leadAvocation/byIdLead/`,
  }, // PROFILING
  RECRUITMENT: {
    GET_BY_ID_RECRUITMENT: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/byIdRecruitment/`,
    POST_CANDIDATE: `${PORTS.RECRUITMENT + API.RECRUITMENT}/candidate`,
    GET_CANDIDATE_ADDRESS_BY_ID_CANDIDATE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateAddress/byIdCandidate/`,
    GET_CANDIDATE_BY_ID: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidate/byId`,
    POST_LOAD_FILE_CANDIDATES: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidate/loadFileCandidates`,
    POST_CANDIDATE_PHONE_NUMBER: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidatePhoneNumber`,
    PUT_CANDIDATE_PHONE_NUMBER: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidatePhoneNumber/`,
    POST_CANDIDATE_EMAIL_ADDRESS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateEmailAddress`,
    PUT_CANDIDATE_EMAIL_ADDRESS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateEmailAddress/`,
    GET_DOCUMENT_RECRUITMENT: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/documents/`,
    GET_CANDIDATE_EMAIL_ADDRESS_BY_ID_CANDIDATE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateEmailAddress/byIdCandidate/`,
    GET_CANDIDATE_PHONE_NUMBER_BY_ID_CANDIDATE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidatePhoneNumber/byIdCandidate/`,
    PUT_CANDIDATE: `${PORTS.RECRUITMENT + API.RECRUITMENT}/candidate/`,
    GET_CANDIDATE: `${PORTS.RECRUITMENT + API.RECRUITMENT}/candidate/`,
    GET_WORK_LIST: `${PORTS.RECRUITMENT}/byIdRecruitment`,
    POST_GET_WORK_LIST: `${PORTS.RECRUITMENT + API.RECRUITMENT}/workList`,
    POST_GET_GET_STATS: `${PORTS.RECRUITMENT + API.RECRUITMENT}/getStats`,
    POST_GET_CANDIDATE_COINCIDENCES: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidate/coincidences`,
    GET_QUESTIONNAIRE_ANSWERS_BY_ID_RECRUITMENT: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/questionnaireAnswers/byIdRecruitment/`,
    POST_QUESTIONNAIRE_ANSWERS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/questionnaireAnswers`,
    POST_CANDIDATE_COMMENTS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateComments`,
    POST_GET_CANDIDATE_COMMENTS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateComments/query`,
    POST_CANDIDATE_ADDRESS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateAddress`,
    PUT_INTERVIEW_FACE_TO_FACE_CONCLUDE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/interview/faceToface/conclude/`,
    PUT_INTERVIEW_FACE_TO_FACE_DISCARD: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/interview/faceToface/discard/`,
    PUT_CANDIDATE_COMMENTS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateComments/`,
    POST_GET_INTERVIEW_COMMENTS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateComments/interview/query`,
    PUT_CANDIDATE_ADDRESS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidateAddress/`,
    GET_ALL_DOCUMENTS_BY_ID_CANDIDATE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/documents/byIdCandidate`,
    GET_DOCUMENTS_CANDIDATE_AVAILABLE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/documents/candidate/available/`,
    POST_DOCUMENTS_CANDIDATE_REQUIRED: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/documents/candidate/required/`,
    POST_RECRUITMENT: PORTS.RECRUITMENT + API.RECRUITMENT,
    GET_DOCUMENTS_CANDIDATE_AVIABLE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/documents/candidate/available/`,
    GET_CANDIDATE_PROSPECT_FILE_REPORT: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidate/prospectFileReport/`,
    GET_INDUCTION_COURSES: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionCourses/`,
    GET_INDUCTION_COURSES_SCHEDULED: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionCourses/scheduled/`,
    POST_INDUCTION_COURSES_SCHEDULED: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionCourses/scheduled/`,
    POST_COURSES_ENROLL_CANDIDATE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/courses/enrollCandidate`,
    GET_ATTENDANTS_BY_INDUCTION_COURSE_BY_ID_RECRUITMENT: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidate/attendants/byInductionCourse/byIdRecruitment/`,
    GET_INDUCTION_TEST_RESULT_BY_ID_REC_COURSE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionTestResult/byIdRecruitment/byIdCourse/`,

    POST_GUEST_COINCIDENCES: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/guest/coincidences`,
    POST_GET_APPOINMENT_STATS: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/appointment/stats/`,
    POST_APPOINMENT_CHECK_IN: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/appointment/checkIn`,
    PUT_APPOINMENT_CHECK_IN: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/appointment/checkIn/`,

    POST_GET_LEADER_INTERVIEW_COINCIDENCES: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/leaderInterview/coincidences`,
    PUT_CANDIDATE_ATTENDANTS_REALLOCATE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidate/attendants/reallocate/`,
    POST_GET_INDUCTION_COURSES_SCHEDULED: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionCourses/scheduled`,
    GET_CANDIDATE_ATTENDANTS_BY_ID_COURSE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/candidate/attendants/byIdCourse/`,
    POST_GET_INDUCTION_COURSES_SCHEDULE_COMBO_BOX: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionCourses/scheduled/comboBox`,
    GET_COURSES_STATS: `${PORTS.RECRUITMENT + API.RECRUITMENT}/courses/stats/`,
    POST_COACHES_COURSES_SEARCH: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/coaches/courses/search`,
    POST_COACHES_COURSES_SEARCH_COMBO_BOX: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/coaches/courses/search/comboBox`,

    PUT_INDUCTION_COURSE_START: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionCourses/start/`,
    POST_UPLOAD_TEST_DOCUMENT: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionTestDocument/uploadTestDocument`,
    GET_INDUCTION_TEST_RESULT_BY_INDUCTION_COURSE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionTestResult/byInductionCourse/`,
    POST_INDUCTION_TEST_RESULTS_ACTUAL_GRADE: `${PORTS.RECRUITMENT +
      API.RECRUITMENT}/inductionTestResults/actualGrade`,
  }, // RECRUITMENT
  RECRUITMENT_AGENDA: {
    POST_SCHEDULE_CANDIDATE: `${PORTS.RECRUITMENT_AGENDA +
      API.RECRUITMENT_AGENDA}/interview/scheduleCandidate`,
    PUT_SCHEDULE_CANDIDATE: `${PORTS.RECRUITMENT_AGENDA +
      API.RECRUITMENT_AGENDA}/interview/`,
    GET_SCHEDULE_CANDIDATE: `${PORTS.RECRUITMENT_AGENDA +
      API.RECRUITMENT_AGENDA}/interview/byIdEvent/`,
    POST_INTERVIEW_COMMENT: `${PORTS.RECRUITMENT_AGENDA +
      API.RECRUITMENT_AGENDA}/interview/comments`,
    GET_EVENTS: `${PORTS.RECRUITMENT_AGENDA + API.RECRUITMENT_AGENDA}/events/`,
    POST_EVENT: `${PORTS.RECRUITMENT_AGENDA + API.RECRUITMENT_AGENDA}/event`,
    POST_GET_SEARCH_ATTENDANT: `${PORTS.RECRUITMENT_AGENDA +
      API.RECRUITMENT_AGENDA}/searchAttendant`,
    GET_EVENT_BY_ID_EMPLOYEE: `${PORTS.RECRUITMENT_AGENDA +
      API.RECRUITMENT_AGENDA}/event/byIdEmployee/`,
    PUT_EVENT_CANCEL: `${PORTS.RECRUITMENT_AGENDA +
      API.RECRUITMENT_AGENDA}/event/cancel/`,
    PUT_EVENT: `${PORTS.RECRUITMENT_AGENDA + API.RECRUITMENT_AGENDA}/event/`,
  }, // RECRUITMENT_AGENDA
  RECRUITMENT_COURSES: {}, // RECRUITMENT_COURSES
  RECRUITMENT_FILE: {
    CANDIDATE_INFORMATION_BY_ID: `${PORTS.RECRUITMENT_FILE +
      API.RECRUITMENT_FILE}/candidate/information/byId/`,
    GET_REFERENCE_BY_ID_RECRUITMENT: `${PORTS.RECRUITMENT_FILE +
      API.RECRUITMENT_FILE}/recruitment/references/byIdRecruitment/`,
    GET_REFERENCES_EMAILS: `${PORTS.RECRUITMENT_FILE +
      API.RECRUITMENT_FILE}/recruitment/references/emails/`,
    GET_REFERENCES_PHONE_NUMBERS: `${PORTS.RECRUITMENT_FILE +
      API.RECRUITMENT_FILE}/recruitment/references/phonesNumbers/`,
    PUT_REFERENCES: `${PORTS.RECRUITMENT_FILE +
      API.RECRUITMENT_FILE}/recruitment/references/`,
    POST_REFERENCES_COMMENT: `${PORTS.RECRUITMENT_FILE +
      API.RECRUITMENT_FILE}/recruitment/references/comment`,
  }, // RECRUITMENT_FILE
  REPOSITORY: {
    POST_FILES_LOAD: `${PORTS.REPOSITORY + API.REPOSITORY}/files/load`,
    GET_PREVIEW_DOCUMENT: `${PORTS.REPOSITORY +
      API.REPOSITORY}/document/preview/`,
    DOWNLOAD_DOCUMENT: `${PORTS.REPOSITORY +
      API.REPOSITORY}/document/download/`,
    POST_PHOTO_LOAD_AVATAR: `${PORTS.REPOSITORY +
      API.REPOSITORY}/loadPhotoFile/avatar`,
    DOCUMENT: `${PORTS.REPOSITORY + API.REPOSITORY}/document/document`,
    GET_DOCUMENT: `${PORTS.REPOSITORY + API.REPOSITORY}/document/`,
  }, // REPOSITORY
  REPOSITORY_NODE: {}, // REPOSITORY_NODE
  LOGIN_USER: {
    START_SESSION: `${PORTS.LOGIN_USER + API.LOGIN}/session/start`,
    END_SESSION: `${PORTS.LOGIN_USER + API.LOGIN}/session/end`,
    PASSWORD_REMINDER: `${PORTS.LOGIN_USER}/api/login/passwordReminder/`,
    LOGOUT: `/logout`,
  }, // LOGIN_USER
  SYSTEM_CONFIGURATION: {
    LOGIN: `${PORTS.SYSTEM_CONFIGURATION}/api/login`,
    POST_PASSWORD_REQUEST: `${PORTS.SYSTEM_CONFIGURATION}/api/login/PasswordRequest`,
    POST_PASSWORD_CHECK: `${PORTS.SYSTEM_CONFIGURATION}/api/login/passwordRequest/check`,
    POST_PASSWORD_RECOVERED: `${PORTS.SYSTEM_CONFIGURATION}/api/login/systemUser/Password/`,
    GET_MESSAGES_BY_ID_LANGUAGE: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/messages/byIdLanguage`,
    // -------- CHANGE POR AND API --------//
    GET_COMPONENTS_BY_ID_COMPANY_ID_SECTION: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/components/byIdCompanyIdSection`,
    POST_AUDITRAIL: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/audiTrail`,
    GET_COMPONENTS_BY_ID_COMPANY_ID_SCREEN_CODE: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/components/byIdCompanyIdScreenCode`,
    GET_SECTION_BY_ID_COMPANY: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/section/byIdCompany`,
    GET_MENU_BY_ID_USER: `${PORTS.SYSTEM_CONFIGURATION +
      API.MENU}/byIdUser/orderByShowOrder`,
    POST_AUDI_TRAIL: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/audiTrail`,
    GET_SCREEN_NAVI: `${PORTS.SYSTEM_CONFIGURATION + API.MENU}/screenNavi/`,
    GET_FRONT_PARAMETERS: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/parameter/frontParameters/`,
    GET_DATE_FROM_DATABASE: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/dateDataBase`,
    GET_TIME_ZONES_BY_ID_COMPANY: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/timeZones/byIdCompany/`,
    GET_RESULT_BUTTON_BY_ID_SECTION: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/resultButton/byIdSection/`,
    POST_EMPLOYEE_CONFIG: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/employeeConfig`,
    PUT_EMPLOYEE_CONFIG: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/employeeConfig/`,
    PUT_EMPLOYEE_CONFIG_CHECK_ALL: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/employeeConfig/checkAll`,
    GET_EMPLOYEE_CONFIG_BY_ID_MANAGER: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/employeeConfig/byIdManager/`,
    POST_GET_EMPLOYEE_CONFIG_SEARCH: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/employee/search/config`,
    POST_GET_REVIEW_RESULTS_REVIEW_SURVEY_BY_ID: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/reviewResults/reviewSurvey/byId`,
    POST_REVIEW_RESULT_ANSWER_REVIEW_SURVEY_GRADE: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/reviewResult/answer/reviewSurveyGrade`,
    POST_GET_COINCIDENCES_COLUMNS: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/config/coincidencesColumns`,
    GET_MENU_TEMPLATE: `${PORTS.SYSTEM_CONFIGURATION}${API.API}/menu/template`,
    GET_CUSTOMER_STATS: `${PORTS.SYSTEM_CONFIGURATION}${API.API}/MasterSystemStat/customer/stats`,
  }, // SYSTEM_CONFIGURATION
  SALES: {
    POST_GET_EMPLOYEE_SEARCH_REFERENCED: `${PORTS.SALES +
      API.SALES}/employee/search/referenced`,
    GET_ALL_WORK_TEAM_ASSIGNED_COMBO_BOX: `${PORTS.SALES +
      API.SALES}/employeeWorkTeam/WorkTeamAssigned/all/comboBox`,
    GET_ALL_WORK_TEAM_ASSIGNED: `${PORTS.SALES +
      API.SALES}/employeeWorkTeam/WorkTeamAssigned/all`,
    GET_LEADS_INVESTEMENT: `${PORTS.SALES +
      API.SALES}/leadInvestment/byIdLead/`,
    POST_LEAD_INVESTMENT: `${PORTS.SALES + API.SALES}/leadInvestment`,
    GET_ASSIGNMENT_AVAILABLE_LEADS: `${PORTS.SALES +
      API.SALES}/lead/availableLeads/`,
    GET_SEARCH_SALESMAN: `${PORTS.SALES + API.SALES}/employee/search/salesman`,
    GET_LEAD_HISTORY_TRANSACTION: `${PORTS.SALES +
      API.SALES}/lead/historyTransaction`,
    GET_LEAD_PORTFOLIO_INVESTMENT_STATS: `${PORTS.SALES +
      API.SALES}/lead/investmentPortfolio/byIdLead/`,
    POST_LEAD_HISTORY: `${PORTS.SALES + API.SALES}/lead/History`,
    GET_LEAD_MARKETING_INFORMATION: `${PORTS.SALES +
      API.SALES}/lead/marketing/rawInfo/`,
    GET_LEAD_INFORMATION: `${PORTS.SALES +
      API.SALES}/lead/information/byIdLead/`,
    GET_LEAD_REPOSITORY_ALL_DOCUMENTS: `${PORTS.SALES +
      API.SALES}/lead/allDocuments/byIdLead/`,
    GET_LEAD_EMAIL_ADDRESSES_BY_ID_LEAD: `${PORTS.SALES +
      API.SALES}/lead/information/byIdLead`,
    GET_LEAD_ORIGIN: `${PORTS.SALES + API.SALES}/lead/Origin/byIdLead`,
    GET_SALESMAN_BY_ID_COMPANY: `${PORTS.SALES +
      API.SALES}/employee/search/salesman/`,
    GET_EMPLOYEES_BY_ID_COMPANY: `${PORTS.SALES + API.SALES}/employee/search/`,
    GET_LEAD_COMMENTS: `${PORTS.SALES +
      API.SALES}/leadComments/byIdLeadIdSection/`,
    POST_LEAD_COMMENTS: `${PORTS.SALES + API.SALES}/leadComments`,
    GET_REQUEST_DOCUMENTS: `${PORTS.SALES + API.SALES}/lead/requestDocuments`,
    GET_POST_REQUEST_DOCUMENTS: `${PORTS.SALES +
      API.SALES}/lead/requestDocuments`,
    POST_ADD_CUSTOMER_TRANSACTION: `${PORTS.SALES +
      API.SALES}/customerTransaction`,
    PUT_UPDATE_CUSTOMER_TRANSACTION: `${PORTS.SALES +
      API.SALES}/customerTransaction`,
    GET_CUSTOMER_TRANSACTION_BY_ID: `${PORTS.SALES +
      API.SALES}/customerTransaction`,
    PUT_CUSTOMER_REJECT_TRANSACTION: `${PORTS.SALES +
      API.SALES}/customerTransaction/rejectTransaction`,
    PUT_CUSTOMER_APPROVE_TRANSACTION: `${PORTS.SALES +
      API.SALES}/customerTransaction/approveTransaction`,
    PUT_CUSTOMER_REQUEST_TRANSACTION: `${PORTS.SALES +
      API.SALES}/customerTransaction/requestTransaction`,
    GET_CUSTOMER_TRANSACTION_INFO_BY_ID: `${PORTS.SALES +
      API.SALES}/customerTransaction/information`,
    POST_ADD_TRANSACTION_DOCUMENT: `${PORTS.SALES +
      API.SALES}/transactionDocument`,
    PUT_UPDATE_TRANSACTION_DOCUMENT: `${PORTS.SALES +
      API.SALES}/transactionDocument`,
    PUT_REJECT_TRANSACTION_DOCUMENT: `${PORTS.SALES +
      API.SALES}/transactionDocument/rejectTransactionDocument`,
    PUT_APPROVE_TRANSACTION_DOCUMENT: `${PORTS.SALES +
      API.SALES}/transactionDocument/approveTransactionDocument`,
    GET_TRANSACTION_DOCUMENT_BY_ID_CUSTOMER_TRANSACTION: `${PORTS.SALES +
      API.SALES}/transactionDocument/byIdCustomerTransaction`,
    PUT_TRANSACTION_CANCEL_REQUEST_DOCUMENT: `${PORTS.SALES +
      API.SALES}/transactionDocument/cancelRequestDocuments`,
    GET_AVAILABLE_TRANSACTION_DOCUMENT: `${PORTS.SALES +
      API.SALES}/transactionDocument`,
    POST_DASHBOARD_TEAM_STATS: `${PORTS.SALES +
      API.SALES}/reports/dashboardTeamStats`,
    POST_GET_CUSTOMER_COINCIDENCES: `${PORTS.SALES +
      API.RETAIL}/customer/coincidences`,
  }, // SALES
  CATALOGS: {
    POST_GET_ALL_LANGUAGES_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS_CONFIG}/masterLanguaje/all/combobox`,
    POST_GET_ALL_LANGUAGES: `${PORTS.CATALOGS +
      API.CATALOGS_CONFIG}/masterLanguaje/all`,
    GET_REPORT_TYPE_BY_ID_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/reportType/byId/comboBox/`,
    GET_REPORT_TYPE_BY_ID: `${PORTS.CATALOGS + API.CATALOGS}/reportType/byId/`,
    GET_ALL_CATALOGS_CLOSING: `${PORTS.CATALOGS +
      API.API}/catalogsStatementAccount/iboffice/closing/catalogs/all`,
    GET_INTERNAL_COMPLETION_REASON_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/internalCompletionReason/all/comboBox/`,
    GET_REPORT_QUERY_TYPE_BY_ID_SECTION_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/reportQueryType/byIdSection/comboBox/`,
    GET_REPORT_QUERY_TYPE_BY_ID_SECTION: `${PORTS.CATALOGS +
      API.CATALOGS}/reportQueryType/byIdSection/`,
    GET_QUERY_INTERVAL_REPORT_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/queryIntervalReport/all/comboBox/`,
    GET_QUERY_INTERVAL_REPORT_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/queryIntervalReport/all/`,
    GET_REPORT_TYPE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/reportType/all/comboBox/`,
    GET_REPORT_TYPE_ALL: `${PORTS.CATALOGS + API.CATALOGS}/reportType/all/`,
    GET_KINSHIP_ALL: `${PORTS.CATALOGS + API.CATALOGS}/kinship/all/`,
    GET_KINSHIP_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/kinship/all/comboBox/`,
    GET_MUNICIPALITY_SEARCH_BY_ID_STATE_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/municipality/search/byIdState/comboBox/`,
    GET_COUNTRY_STATE_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/country/state/comboBox/`,
    GET_COUNTRY_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/country/all/comboBox/`,
    GET_PHONE_TYPE_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/phonetypes/all/comboBox/`,
    GET_ASSIGNMENT_RULE_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/AssignmentRule/all/`,
    GET_REFERENCES_TYPE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/referencesType/all/comboBox/`,
    GET_REFERENCES_TYPE_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/referencesType/all/`,
    POST_ASSIGNMENT_RULE: `${PORTS.CATALOGS + API.CATALOGS}/AssignmentRule`,
    UPDATE_ASSIGNMENT_RULE_BY_ID: `${PORTS.CATALOGS +
      API.CATALOGS}/AssignmentRule/`,
    GET_ASSIGNMENT_TYPE_COMBOBOX_BY_ID_RULE: `${PORTS.CATALOGS +
      API.CATALOGS}/AssignmentType/all/comboBox/`,
    GET_QUERY_FIELD_BY_ID_SECTION: `${PORTS.CATALOGS +
      API.CATALOGS}/queryField/byIdSection`,
    GET_QUERY_FIELD_BY_ID_SECTION_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/queryField/byIdSection/comboBox`,
    GET_OPERATORS_BY_ID_QUERY_FIELD: `${PORTS.CATALOGS +
      API.CATALOGS}/queryFieldOperator/byIdQueryField`,
    GET_OPERATORS_BY_ID_QUERY_FIELD_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/queryFieldOperator/byIdQueryField/comboBox`,
    GET_LEAD_CONTACT_STATUS: `${PORTS.CATALOGS +
      API.CATALOGS}/leadContactStatus/All`,
    GET_LEAD_CONTACT_STATUS_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/leadContactStatus/All/comboBox`,
    GET_LEAD_CONTACT_STATUS_BY_ID: `${PORTS.CATALOGS +
      API.CATALOGS}/leadContactStatus`,
    GET_INVESTMENT_CATALOGS: `${PORTS.CATALOGS +
      API.CATALOGS}/InvestmentCategory/all/`,
    GET_INVESTMENT_EXP_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/InvestmentExperience/all/comboBox/`,
    GET_INVESTMENT_AMOUNT_RANGE_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/InvestmentAmountRange/all/comboBox/`, // USPgetAllInvestmentAmountRange
    GET_INVESTMENT_LEVEL_CREDIT_CARD_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/creditCardRange/all/comboBox/`,
    GET_INVESTMENT_LIMIT_CREDIT_CARD_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/CreditCardRangeLabel/all/comboBox/`,
    GET_INVESTMENT_AVOCATION_CATEGORY_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/avocationCategory/all/`,
    GET_INVESTMENT_AVOCATION_SUBCATEGORY_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/avocationSubcategory/byidAvocationCategory/`,
    GET_INVESTMENT_PROPERTY_TYPE_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/propertyType/all/comboBox/`,
    GET_INVESTMENT_OWNERSHIP_TYPE_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/ownershipType/all/comboBox/`,
    GET_ALL_AMOUNT_RANGE_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/amountRange/all/comboBox`,
    GET_ALL_AMOUNT_RANGE: `${PORTS.CATALOGS + API.CATALOGS}/amountRange/all`,
    GET_ALL_TRANSACTION_STATUS_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/transactionStatus/all/comboBox`,
    GET_ALL_TRANSACTION_STATUS: `${PORTS.CATALOGS +
      API.CATALOGS}/transactionStatus/all`,
    GET_NATIONALITY_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/nationality/all/comboBox/`,
    GET_MARITAL_STATUS_CATALOG: `${PORTS.CATALOGS +
      API.CATALOGS}/maritalStatus/all/comboBox/`,
    GET_ALL_COUNTRY: `${PORTS.CATALOGS + API.CATALOGS}/country/all`,
    GET_ALL_COUNTRY_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/country/all/comboBox`,
    GET_ALL_TRANSACTION_TYPE: `${PORTS.CATALOGS +
      API.CATALOGS}/transactionType/all`,
    GET_ALL_TRANSACTION_TYPE_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/transactionType/all/comboBox`,
    GET_ALL_LEVERAGE: `${PORTS.CATALOGS + API.CATALOGS}/leverage/all`,
    GET_ALL_LEVERAGE_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/leverage/all/comboBox`,
    GET_ALL_PUBLISHING: `${PORTS.CATALOGS + API.CATALOGS}/publishing/all`,
    GET_ALL_PUBLISHING_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/publishing/all/comboBox`,
    GET_ALL_TRANSACTION_TYPE_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/transactionType/all/comboBox`,
    GET_ALL_PAYMENT_METTHOD: `${PORTS.CATALOGS +
      API.CATALOGS}/paymentMethod/all`,
    GET_ALL_PAYMENT_METTHOD_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/paymentMethod/all/comboBox`,
    GET_ALL_PROFESSION_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/Profession/all/comboBox`,
    GET_ALL_PROFESSION: `${PORTS.CATALOGS + API.CATALOGS}/Profession/all`,
    GET_SOCIOECONOMIC_STATUS_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/socioeconomicStatus/all/comboBox`,
    GET_SOCIOECONOMIC_STATUS: `${PORTS.CATALOGS +
      API.CATALOGS}/socioeconomicStatus/all`,
    GET_EMAIL_TEMPLATES_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/EmailTemplate/all/comboBox`,
    GET_EMAIL_TEMPLATES: `${PORTS.CATALOGS + API.CATALOGS}/EmailTemplate/all`,
    GET_REPORT_QUERY_BY_ID_SECTION_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/ReportQueryType/byIdSection/comboBox/`,
    GET_REPORT_QUERY_BY_ID_SECTION: `${PORTS.CATALOGS +
      API.CATALOGS}/ReportQueryType/byIdSection/`,
    GET_DEPARTAMENT_BY_ID_COMPANY: `${PORTS.CATALOGS +
      API.CATALOGS}/department/byIdCompany/`,
    GET_DEPARTAMENT_BY_ID_COMPANY_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/department/byIdCompany/comboBox/`,
    GET_JOB_POSITION_BY_ID_DEPARTAMENT: `${PORTS.CATALOGS +
      API.CATALOGS}/jobPosition/byIdDepartment/`,
    GET_JOB_POSITION_BY_ID_DEPARTAMENT_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/jobPosition/byIdDepartment/comboBox/`,
    GET_DEPARTMENT_ALL: `${PORTS.CATALOGS + API.CATALOGS}/department/all/`,
    GET_DEPARTMENT_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/department/all/comboBox/`,
    GET_ORGANIZATION_CHART_BY_ID_POSITION: `${PORTS.CATALOGS +
      API.CATALOGS}/organizationChart/byIdJobPosition/`,
    GET_ORGANIZATION_CHART_BY_ID_POSITION_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/organizationChart/byIdJobPosition/comboBox/`,
    POST_VACANCY: `${PORTS.CATALOGS + API.CATALOGS}/Vacancy`,
    POST_COMPANY_JOB_POSITION: `${PORTS.CATALOGS +
      API.CATALOGS}/CompanyJobPosition`,
    GET_JOB_POSITION: `${PORTS.CATALOGS + API.CATALOGS}/jobPosition/`,
    GET_VACANCY_TYPE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/vacancyType/all/comboBox/`,
    GET_VACANCY_TYPE_ALL: `${PORTS.CATALOGS + API.CATALOGS}/vacancyType/all/`,
    PUT_VACANCY: `${PORTS.CATALOGS + API.CATALOGS}/vacancy/`,
    PUT_COMPANY_JOB_POSITION: `${PORTS.CATALOGS +
      API.CATALOGS}/companyJobPosition/`,
    POST_DEPARTMENT: `${PORTS.CATALOGS + API.CATALOGS}/department`,
    POST_COMPANY_OFFICE: `${PORTS.CATALOGS + API.CATALOGS}/companyOffice`,
    PUT_COMPANY_OFFICE: `${PORTS.CATALOGS + API.CATALOGS}/companyOffice/`,
    GET_CANDIDATE_STATUS_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/candidateStatus/all/`,
    GET_CANDIDATE_STATUS_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/candidateStatus/all/comboBox/`,
    GET_JOB_BOARD_ALL: `${PORTS.CATALOGS + API.CATALOGS}/jobBoard/all/`,
    GET_JOB_BOARD_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/jobBoard/all/comboBox/`,
    GET_CONTACT_TYPE_ALL: `${PORTS.CATALOGS + API.CATALOGS}/contactType/all/`,
    GET_CONTACT_TYPE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/contactType/all/comboBox/`,
    GET_JOB_POSITION_ALL_BY_ID_DEPARTMENT: `${PORTS.CATALOGS +
      API.CATALOGS}/jobposition/all/byIdDepartment/`,
    GET_JOB_POSITION_ALL_BY_ID_DEPARTMENT_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/jobposition/all/byIdDepartment/comboBox/`,
    GET_CANDIDATE_CALL_RESULT_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/candidateCallResult/all/`,
    GET_CANDIDATE_CALL_RESULT_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/candidateCallResult/all/comboBox/`,
    GET_RPSTATUS_TRUNKED_CALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/rpstatus/trunkedCall/comboBox/`,
    GET_REJECTION_REASONS_BY_RP_STATUS: `${PORTS.CATALOGS +
      API.CATALOGS}/rejectionReasons/byRPStatus/`,
    GET_REJECTION_REASONS_BY_RP_STATUS_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/rejectionReasons/byRPStatus/comboBox/`,
    GET_DOCUMENT_CATEGORY_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/documentCategory/all/comboBox/`,
    GET_PYSCHOMETRIC_TEST_TYPE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/psychometricTestType/all/comboBox/`,
    GET_PYSCHOMETRIC_TEST_TYPE_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/psychometricTestType/all/`,
    GET_RP_STATUS_PSYCHO_RESULT_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/rpstatus/psychoResult/comboBox/`,
    GET_RP_STATUS_PSYCHO_RESULT: `${PORTS.CATALOGS +
      API.CATALOGS}/rpstatus/psychoResult/`,
    POST_GET_RP_RECOMMENDATION_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/RPRecommendation/all/combobox/`,
    POST_GET_RP_RECOMMENDATION_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/RPRecommendation/all/`,
    GET_INDUCTION_COURSE_REALLOCATION_REASON_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/inductionCourseReallocationReason/all/comboBox/`,
    GET_INDUCTION_COURSE_REALLOCATION_REASON_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/inductionCourseReallocationReason/all/`,
    GET_COMPANY_OFFICE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/companyOffice/all/byIdCompany/comboBox/`,
    GET_EMPLOYEE_TYPE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/employeeType/all/comboBox/`,
    GET_EMPLOYEE_TYPE_ALL: `${PORTS.CATALOGS + API.CATALOGS}/employeeType/all/`,
    GET_COMPANY_OFFICE_BY_ID_JOB_POSITION_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/companyOffice/byIdJobPosition/comboBox`,
    GET_COMPANY_OFFICE_BY_ID_JOB_POSITION: `${PORTS.CATALOGS +
      API.CATALOGS}/companyOffice/byIdJobPosition`,
    POST_GET_WORKING_HOURS_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/WorkingHours/all/comboBox`,
    POST_GET_WORKING_HOURS: `${PORTS.CATALOGS + API.CATALOGS}/WorkingHours/all`,
    GET_COMPANY_OFFICE_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/companyOffice/all/byIdCompany/`,
    POST_GET_MASTER_RECRUITMENT_PHASE: `${PORTS.CATALOGS +
      API.CATALOGS}/masterRecruimentPhase/byIdJobPosition`,
    POST_GET_MASTER_RECRUITMENT_PHASE_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/masterRecruimentPhase/byIdJobPosition/comboBox`,
    GET_MASTER_ACTION_TYPE_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/masterActionType/all/`,
    GET_MASTER_ACTION_TYPE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/masterActionType/all/comboBox/`,
    GET_ALERT_INTERVAL_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/alertInterval/all/comboBox/`,
    GET_INCIDENCE_TYPE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/IncidenceType/all/comboBox/`,
    GET_INCIDENCE_TYPE_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/IncidenceType/all/`,
    GET_BANK_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/bank/all/comboBox`,
    GET_BANK_ALL: `${PORTS.CATALOGS + API.CATALOGS}/bank/all`,
    GET_ALL_REQUEST_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/RequestType/all/comboBox/`,
    GET_ALL_REQUEST: `${PORTS.CATALOGS + API.CATALOGS}/RequestType/all/`,
    POST_GET_RECRUITMENT_PHASE_ALL: `${PORTS.CATALOGS +
      API.CATALOGS}/recruitmentPhase/all/`,
    POST_GET_RECRUITMENT_PHASE_ALL_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/recruitmentPhase/all/comboBox`,
    GET_ALL_REQUEST_STATUS_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/requestStatus/all/comboBox/`,
    GET_ALL_REQUEST_STATUS: `${PORTS.CATALOGS +
      API.CATALOGS}/requestStatus/all/`,
    POST_GET_ALL_MONTH: `${PORTS.CATALOGS + API.CATALOGS}/month/all/`,
    POST_GET_ALL_MONTH_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/month/all/comboBox/`,
    POST_GET_ALL_YEAR: `${PORTS.CATALOGS + API.CATALOGS}/year/all`,
    POST_GET_ALL_YEAR_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/year/all/comboBox`,
    POST_GET_SYSTEM_VIEWS: `${PORTS.CATALOGS +
      API.CATALOGS}/SystemViews/byIdSection/`,
    POST_GET_SYSTEM_VIEWS_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/SystemViews/byIdSection/comboBox/`,
    GET_CATALOG_BALANCE: `${PORTS.CATALOGS + API.CATALOGS}/p2goBalance/all/`,
    GET_CATALOG_BALANCE_COMBO_BOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goBalance/all/comboBox/`,
    /**
     * @name P2GO
     * @description This constants are used in the P2GO module
     */
    // #region
    POST_GET_ALL_COUNTRIES: `${PORTS.CATALOGS + API.CATALOGS}/p2gocountry/all/`,
    POST_GET_ALL_COUNTRIES_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2gocountry/all/combobox/`,

    POST_GET_ALL_BANKS: `${PORTS.CATALOGS + API.CATALOGS}/p2gobanks/all/`,
    POST_GET_ALL_BANKS_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2gobanks/all/combobox/`,

    POST_GET_ALL_CURRENCY: `${PORTS.CATALOGS + API.CATALOGS}/p2goCurrency/all/`,
    POST_GET_ALL_CURRENCY_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goCurrency/all/combobox/`,

    POST_GET_ALL_ACCOUNT_TYPE: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goAccountType/all`,
    POST_GET_ALL_ACCOUNT_TYPE_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goAccountType/all/combobox`,

    POST_GET_ALL_BROKERS_BY_USER: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goBrokers/all/byIdUser/`,
    POST_GET_ALL_BROKERS_BY_USER_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goBrokers/all/byIdUser/combobox/`,

    POST_GET_ALL_TRANSACTION_CATEGORY: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionCategory/all/`,
    POST_GET_ALL_TRANSACTION_CATEGORY_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionCategory/all/combobox/`,

    POST_GET_ALL_TRANSACTION_TYPE: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionType/all/`,
    POST_GET_ALL_TRANSACTION_TYPE_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionType/all/combobox/`,

    POST_GET_ALL_TRANSACTION_ORIGIN: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionOrigin/all/`,
    POST_GET_ALL_TRANSACTION_ORIGIN_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionOrigin/all/combobox/`,

    POST_GET_ALL_TRANSACTION_CONCEPT: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goConcept/all/`,
    POST_GET_ALL_TRANSACTION_CONCEPT_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goConcept/all/combobox/`,

    POST_GET_ALL_EXCHANGE_RATES: `${PORTS.CATALOGS +
      API.BLACK_BOX_CATALOGS}/p2goExchangeRates/all/`,
    POST_GET_ALL_EXCHANGE_RATES_COMBOBOX: `${PORTS.CATALOGS +
      API.BLACK_BOX_CATALOGS}/p2goExchangeRates/all/comboBox/`,

    PUT_SET_IB_OFFICE: `${PORTS.CATALOGS + API.CATALOGS}/p2goUserIBOffice/`,
    GET_ALL_IB_OFFICE: `${PORTS.CATALOGS + API.CATALOGS}/p2goUserIBOffice/all/`,
    GET_ALL_IB_OFFICE_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goUserIBOffice/all/combobox/`,

    POST_GET_ALL_IB_OFFICE: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goUserIBOffice/all/`,
    POST_GET_ALL_IB_OFFICE_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goUserIBOffice/all/combobox/`,

    GET_ALL_ENTERPRISES_BY_ID_USER: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goEnterprise/all`,
    GET_ALL_ENTERPRISES_BY_ID_USER_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goEnterprise/all/combobox`,

    GET_ALL_TRANSACTION_MOVE: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionMove/all`,
    GET_ALL_TRANSACTION_MOVE_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionMove/all/combobox`,

    POST_ADD_BROKER: `${PORTS.CATALOGS + API.CATALOGS}/p2gobrokers/add`,

    GET_TRANSACTION_VIEW: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionView/all/`,
    GET_TRANSACTION_VIEW_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionView/all/combobox`,

    POST_GET_CONCEPT_BANK: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goConceptBank/all/`,
    POST_GET_CONCEPT_BANK_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goConceptBank/all/combobox`,

    GET_PAYMENT_METHOD: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goPaymentMethod/all/`,
    GET_PAYMENT_METHOD_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goPaymentMethod/all/combobox`,

    GET_INCOME_STATEMENT_VIEWS: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goAccountsBalance/all/`, // USPgetAllIncomeStatementViews
    GET_INCOME_STATEMENT_VIEWS_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goAccountsBalance/all/combobox`, // USPgetAllIncomeStatementViews

    GET_TRANSACTION_STATUS: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionStatus/all/`, // USPgetAllTransactionStatus
    GET_TRANSACTION_STATUS_COMBOBOX: `${PORTS.CATALOGS +
      API.CATALOGS}/p2goTransactionStatus/all/combobox`, // USPgetAllTransactionStatus

    POST_ALL_CATALOGS: `${PORTS.CATALOGS + API.API}/catalogAll`,
    POST_ALL_CATALOGS_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogAll/combobox`,

    GET_ALL_OFFICE_TYPE: `${PORTS.CATALOGS + API.API}/officeType/all`, // USPgetAllOfficeType
    GET_ALL_OFFICE_TYPE_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/officeType/all/combobox`, // USPgetAllOfficeType

    POST_GET_ALL_BROKERS_OFFICE: `${PORTS.CATALOGS +
      API.API}/p2gobrokersOffice/all`, // USPgetAllBrokersByIdIBOffice
    POST_GET_ALL_BROKERS_OFFICE_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/p2gobrokersOffice/all/combobox`, // USPgetAllBrokersByIdIBOffice

    POST_GET_ALL_TRANSACTION_BROKERS: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2gobrokers/transaction/all`,
    POST_GET_ALL_TRANSACTION_BROKERS_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2gobrokers/transaction/all/combobox`, // USPgetAllTransactionBrokers

    POST_GET_ALL_TRANSACTION_OFFICES: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/userIBOffice/transaction/all`,
    POST_GET_ALL_TRANSACTION_OFFICES_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/userIBOffice/transaction/all/combobox`, // USPgetAllTransactionOffices

    POST_GET_ALL_TRANSACTION_CONCEPT_BANK: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2goConcept/transaction/all`,
    POST_GET_ALL_TRANSACTION_CONCEPT_BANK_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2goConcept/transaction/all/combobox`, // USPgetAllTransactionConceptBank

    POST_GET_TRANSACTION_IT: `${PORTS.CATALOGS +
      API.BLACK_BOX_CATALOGS}/itTypeCategory/all`,
    POST_GET_TRANSACTION_IT_COMBOBOX: `${PORTS.CATALOGS +
      API.BLACK_BOX_CATALOGS}/itTypeCategory/all/combobox/`,

    POST_GET_ALL_TRANSACTION_CURRENCIES: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2gocurrency/transaction/all`,
    POST_GET_ALL_TRANSACTION_CURRENCIES_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2gocurrency/transaction/all/combobox`, // USPgetAllTransactionCurrencies

    POST_GET_ALL_TRANSACTION_PAYMENT_METHOD: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/paymentMethod/transaction/all`,
    POST_GET_ALL_TRANSACTION_PAYMENT_METHOD_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/paymentMethod/transaction/all/combobox`,
    // USPgetAllTransactionPaymentMethod

    POST_GET_ALL_TRANSACTION_COUNTRIES: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2gocountry/transaction/all`,
    POST_GET_ALL_TRANSACTION_COUNTRIES_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2gocountry/transaction/all/combobox`, // USPgetAllTransactionCountries

    POST_GET_ALL_ENTERPRISES_BY_ID_USER: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2goenterprise/all`,
    POST_GET_ALL_ENTERPRISES_BY_ID_USER_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/p2goenterprise/all/combobox`,
    // USPgetAllEnterprisesByIdUser

    POST_GET_ALL_TRANSACTION_METHODS_OUTPUT: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/methodOutput/transaction/all`,
    POST_GET_ALL_TRANSACTION_METHODS_OUTPUT_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/methodOutput/transaction/all/combobox`,
    // USPgetAllTransactionMethodsOutput
    // #endregion
    GET_ALL_TRANSACTION_FUNCTIONARY: `${PORTS.CATALOGS +
      API.API}/CatalogsBlackBox/P2GOFunctionary/all`,
    GET_ALL_TRANSACTION_FUNCTIONARY_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/CatalogsBlackBox/P2GOFunctionary/all/comboBox`,

    POST_GET_ACCOUNT_CLOSING_YEARS_ALL: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/accountClosing/years/all`,
    POST_GET_ACCOUNT_CLOSING_YEARS_ALL_COMBOBOX: `${PORTS.CATALOGS +
      API.API}/catalogsBlackBox/accountClosing/years/all/combobox`,
    // USPgetAllYearsClosing
  }, // CATALOGS
  BLACK_BOX: {
    POST_STATEMENT_ACCOUNT_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.API}/accountStatements/coincidences`,
    PUT_STATEMENT_ACCOUNT: `${PORTS.BLACK_BOX +
      API.API}/accountStatements/statementAccount/reset`,
    POST_ADD_ACCOUNT: `${PORTS.BLACK_BOX +
      API.API}/AccountStatements/AccountClosingDocument`,
    POST_ACCOUNT_CLOSING: `${PORTS.BLACK_BOX +
      API.API}/accountStatements/accountClosingDocument/close`,
    POST_STATEMENT_STATISTICS: `${PORTS.BLACK_BOX +
      API.API}/AccountStatements/Statistics`,
    POST_CHECKED_STATEMENT: `${PORTS.BLACK_BOX +
      API.API}/AccountStatements/Checked`,
    GET_INCOME_STATEMENT_INFO: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/incomeStatementInfo`, // USPgetIncomeStatementInfo
    GET_INCOME_STATEMENT_COLUMNS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goBalance/incomeStatement/columns`, // USPgetIncomeStatementColumns
    POST_GET_INCOME_STATEMENT_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/incomeStatementCoincidences`, // USPgetIncomeStatementCoincidences
    POST_GET_INCOME_STATEMENT_ACCOUNT_INFO: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/incomeStatement/accountInformation`, // USPgetIncomeStatementAccountInfo
    POST_GET_INCOME_STATEMENT_STATS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goSystemStats/incomeStatement/stats`, // USPgetIncomeStatementStats
    POST_UPLOAD_INCOME_STATEMENT_BALANCE_DOCUMENT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goBalanceDocument`, // USPuploadIncomeStatementDocument
    POST_RESET_INCOME_STATEMENT_BALANCE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/incomeStatement/reset`, // USPresetIncomeStatementBalance
    POST_SET_ACCOUNT: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goAccount`,
    GET_ACCOUNTS_BY_ID_USER: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/P2GOaccount/byUser`,
    GET_ACCOUNTS_BY_ID_USER_COMBOBOX: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/P2GOaccount/byUser/comboBox`,
    GET_TRANSACTION_GO: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2GoTransactionGO/`, // USPsetTransactionGO
    GET_TRANSACTION_GO_STATS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/stats`, // USPsetTransactionGOStats
    PUT_SET_TRANSACTION_GO: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/`,
    POST_UPDATE_IB_OFFICE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/update/office`,
    POST_SEARCH_CUSTOMER: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/search/customer/comboBox`,
    POST_GET_ACCOUNT_BALANCE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/P2GOAccount/accounts/balance`, // USPgetAccountsBalance
    POST_CHECK_UNIQUE_TRANSACTION: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/checkUniqueTransaction`,
    GET_TRANSACTIONS_COLUMNS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/columns`,
    POST_GET_TRANSACTIONS_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/coincidences`,
    POST_GET_EXPENSES: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goBroker/expenses`, // USPgetBrokerExpenses
    POST_GET_DEBIT: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goBroker/debit`, // USPgetBrokersDebit
    GET_ENTERPRISES_COUNTRY_BALANCE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/enterprises/countryBalance`,
    GET_MONTH_BALANCE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/monthbalance`, // USPgetMonthBalance
    GET_MONTH_BALANCE_COMBOBOX: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/monthbalance/combobox`, // USPgetMonthBalance
    POST_GET_CURRENCY_CHANGE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/CurrencyChange`,
    PUT_DISCARD_TRANSACCTION: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/discard/transaction`,
    PUT_ECHANGE_RATE: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goExchangeRate/`,
    GET_TRANSACTION_GO_INFO: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/info`,
    GET_TRANSACTION_GO_DOCUMENTS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/all/documents/byIdTransactionGo`,
    ATTACH_TRANSACTION_DOCUMENT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/transactionDocument/attach`,
    POST_GET_TRANSACTION_COINCIDENCES_ACOUNTS_DETAILS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/broker/coincidences`,
    POST_GET_TRANSACTION_COINCIDENCES_ACOUNTS_DETAILS_COLUMNS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/broker/columns`,
    POST_CHECK_EXCHANGE_RATE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/check/exchangeRate`,
    GET_BALANCE: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goBalance/all`,
    POST_ADD_BALANCE: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goBalance/add`,
    POST_DOCUMENT_BALANCE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance`,
    POST_GET_TRANSACTION_CONCILIATE_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/transaction/conciliateCoincidences`, // USPgetTransactionGOConciliateCoincidences
    POST_GET_INCOME_STATEMENT_CONCILIATE_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/incomeStatementConciliateCoincidences`, // USPgetIncomeStatementConciliateCoincidences
    POST_GET_TRANSACTIONS_BALANCE_INFO: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/transactionInfo`,
    PUT_UPDATE_CONCILIATE_TRANSACTION: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/conciliate`,
    PUT_UPDATE_ACCOUNT_BALANCE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance`,
    POST_CONCILIATE_TRANSACTION: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/conciliate`, // USPconciliateTransactionGO
    PUT_UNDO_CONCILIATE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/conciliate/undo`, // USPundoConciliateAccountBalance
    POST_CLOSE_ACCOUNT_BALANCE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goBalance/close`, // USPcloseAccountBalance
    GET_ALL_BROKER: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goBroker/all`, // USPgetAllP2GOBrokers
    PUT_BROKER: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goBroker`, // USPupdateP2GOBrokers
    POST_GET_ACCOUNTS_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccount/coincidences`, // USPgetP2GOAccountCoincidences
    POST_GET_ENTERPRISE_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goEnterprise/coincidences`, // USPgetEnterpriseCoincidences
    POST_GET_ACCOUNTS_BY_ID: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccount/byId`, // USPgetP2GOAccountById
    GET_ENTERPICE_BY_ID: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goEnterprise/byId`, // USPgetEnterpriseById
    GET_ALL_COMMISSION_SCHEMA_BY_ID: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/commissionSchema/all`, // USPgetAllP2GOCommission
    POST_COMMISSION_SCHEMA: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/commissionSchema`, // USPaddP2GOCommission
    POST_GET_ENTERPRICE_PARAMS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/enterpriseParams`, // USPgetEnterpriseParams
    PUT_ENTERPRICE_PARAMS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/enterpriseParams`, // USPupdateEnterpriseParams
    PUT_ENTERPRICE: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goEnterprise`, // USPupdateEnterprise
    POST_GET_TRANSACTION_COMMENT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goTransactionComment`,
    PUT_SET_TRANSACTION_COMMENT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goTransactionComment`,
    GET_TRANSACTIONS_CREDIT_STATS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/creditStats`, // USPgetTransactionCreditStats
    POST_GET_OFFICE_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goOffice/coincidences`,
    POST_OFFICE: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goOffice`, // USPaddOfficeGO
    GET_OFFICE: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goOffice/byId`, // USPgetOfficeGOById
    POST_GET_CREDIT_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/creditCoincidences`, // USPgetTransactionGOCreditCoincidences
    POST_GET_COINCIDENCES_COLUMNS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/coincidencesColumns`, // USPgetCoincidencesColumns
    POST_GET_DEBIT_STATS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/debitStats/`, // USPgetTransactionGODebitStats
    PUT_BROKERS_OFFICE: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2gobrokersOffice`, // USPupdateBrokersByIBOffice
    PUT_OFFICE: `${PORTS.BLACK_BOX + API.BLACK_BOX}/p2goOffice`, // USPupdateOfficeGO
    POST_GET_DEBIT_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/debitCoincidences`, // USPgetTransactionGODebitCoincidences
    POST_GET_BALANCE_STATISTICS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/statistic`, // USPgetBalanceStatistic
    POST_GET_STATS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/stats`, // USPgetBalanceStats
    POST_GET_ENTERPRISE_STATISTICS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/statistic/enterprise`,
    POST_GET_TRANSACTION_STATISTICS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/statistic/transactions`,
    POST_GET_BALANCE_STATS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/stats`,
    POST_GET_BALANCE_STATISTICS_CHART: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/statistic/chart`,
    POST_GET_INCOME_STATEMENT_BALANCE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/incomeStatement/balance`,
    POST_GET_INCOME_STATEMENT_STATISTICS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/incomeStatement/statistic`,
    POST_GET_INCOME_BROKER_GROUP: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goBrokerGroup/combobox`,
    POST_CONCILIATE_INCOME_STATEMENT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/conciliate/incomeStatement`,
    POST_CHECK_CONCILIATE_INCOME_STATEMENT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2goAccountBalance/checkConciliate/incomeStatement`,

    POST_GET_TRANSACTION_GO: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO`,

    POST_GET_P2GO_TRANSACTION_GO_ADMIN: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/TransactionAdmin`,

    PUT_POST_GET_TRANSACTION_GO_ADMIN: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/TransactionAdmin`,

    POST_CUSTOMER_DETAIL: `${PORTS.BLACK_BOX + API.BLACK_BOX}/customer/detail`,

    POST_COINCIDENCE_BY_ID_USER: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/transactionPm/coincidences/byIdCustomer`,
    POST_GET_DOCUMENTS_BY_ID_CUSTOMER: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/SystemUser/Documents/ByIdCustomer`,

    POST_GET_CUSTOMER_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/customer/Coincidences`,

    POST_GET_CUSTOMER_STATS: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/systemUser/Customer/Stats`,
    PUT_POST_DEACTIVATE_SYSTEM_USER: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/systemUser/Deactivate`,

    PUT_UPDATE_CUSTOMER_DOCUMENT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/customerDocument`,
    // ==================================================
    POST_GET_ALL_ACCONUNT_CLOSING: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/accountClosing/all`,
    POST_GET_ALL_YEARS_CLOSING: `${PORTS.CATALOGS +
      API.BLACK_BOX_CATALOGS}/accountClosing/years/all`,
    POST_GET_ALL_YEARS_CLOSING_COMBOBOX: `${PORTS.CATALOGS +
      API.BLACK_BOX_CATALOGS}/accountClosing/years/all/combobox`,
    POST_GET_ACCOUNT_CLOSING_COUNTRY: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/AccountClosing/InCountry`,
    POST_GET_ACCOUNT_CLOSING_ACCOUNT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/AccountClosing/InAccount`,
    POST_GET_CLOSING_IN_ENTERPRISE: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/p2GoTransactionGO/AccountClosing/InEnterprise`,
    GET_COMPONENTS_BY_ID_COMPANY_ID_SCREEN_CODE: `${PORTS.SYSTEM_CONFIGURATION +
      API.SYSTEM_CONFIGURATION}/components/company`,
    PUT_SET_CUSTOMER_COMMENT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/CustomerComment`,
    POST_GET_COMMENTS_BY_ID_CUSTOMER: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/CustomerComment/ByIdCustomer`,
    POST_GET_VALIDATED_CUSTOMER_ACCOUNT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/systemUser/Validate/CustomerAccount`,
    PUT_VALIDATE_CUSTOMER_ACCOUNT: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/Customer/ValidateAccount`,
    POST_TRANSACTION_PM_INFO: `${PORTS.BLACK_BOX +
      API.BLACK_BOX}/transactionPm/info`,
    POST_GET_STATEMENT_ACCOUNT_CONCILIATE_COINCIDENCES: `${PORTS.BLACK_BOX +
      API.API}/accountStatements/coincidences/conciliate`,
    POST_GET_ALL_ACCOUNTS: `${PORTS.BLACK_BOX}${API.API}/AccountStatements/p2goAccount/transaction/all`,
    PUT_SET_TRANSACTION_GO_CLOSING: `${PORTS.BLACK_BOX}${API.BLACK_BOX}/p2GoTransactionGO/closing`,
    POST_GET_TRANSACTION_GO_CLOSING: `${PORTS.BLACK_BOX}${API.API}/accountStatements/closing/transaction`,
    POST_DISCARDED_STATEMENT_ACCOUNT: `${PORTS.BLACK_BOX}${API.API}/AccountStatements/Discarted`,
    POST_UNDO_CONCILIATE_STATEMENT_ACCOUNT: `${PORTS.BLACK_BOX}${API.API}/AccountStatements/UndoConciliate`,
  }, // BLACK_BOX
  REPORTS: {
    POST_EXCEL_PARAMENTERS_ENCRIPT: `${PORTS.REPORTS +
      API.REPORTS}/excel/parameters/encript`,
    GET_EXCEL: `${PORTS.REPORTS + API.REPORTS}/excel`,
    GET_PDF_TRANSACTION_PM_INFO: `${PORTS.REPORTS +
      API.REPORTS_BLACKBOX}/transactionPM/info/pdf`,
  }, // REPORTS
  PAY_TO_GO: {
    POST_GET_CUSTOMER_COINCIDENCES: `${PORTS.PAY_TO_GO +
      API.PAY_TO_GO}/customer/Coincidences`,
    POST_GET_CUSTOMER_STATS: `${PORTS.PAY_TO_GO +
      API.PAY_TO_GO}/systemUser/Customer/Stats`,
  },
  ALPHA: {
    ENCRYPT_TRANSACTION: `${PORTS.ALPHA}${API.API}/reportsClient/encript/transactionInfo`,
    GET_TRANSACTION_PDF: `${PORTS.ALPHA}${API.API}/reportsClient/pdf/transactionInfo?value=`,
    GET_MENU_TEMPLATE: `${PORTS.ALPHA}${API.API}/menu/template`,
    POST_PAYMENT_TYPE: `${PORTS.ALPHA}${API.API}/catalogsClient/paymentType/all/combobox`,
    POST_ACCEPT_TERMS: `${PORTS.BLACK_BOX}${API.API}/client/customer/AcceptTerms`,
    GET_TERMS_AND_CONDITIONS: `${PORTS.BLACK_BOX}${API.API}/Client/Parameter/TermsConditions`,
    POST_GET_ACCOUNT_CUSTOMER: `${PORTS.ALPHA + API.ALPHA}/customer/account`,
    ALFA_LOGIN: `${`${PORTS.BLACK_BOX}/api/Login`}`,
    GET_PROFILE_BY_SYSTEM_USER: `${`${PORTS.ALPHA}/api/client` +
      `/systemUser/profileById`}`,
    POST_GET_ANSWERS_ACCOUNT: `${`${PORTS.ALPHA}/api/client/ReviewResult/Customer/Questionnaire`}`,
    PUT_ANSWERS_ACCOUNT: `${`${PORTS.ALPHA}/api/client/ReviewResult/Customer/Questionnaire/`}`,
    DOCUMENT: `${PORTS.ALPHA + API.ALPHA_REPOSITORY}/document/document`,
    CUSTOMER_DOCUMENT_ATTACH: `${PORTS.BLACK_BOX}/api/clientRepository/transactionDocument`,
    GET_CUSTOMER_DOCUMENT: `${PORTS.ALPHA}/api/client/transactionDocument/all`,
    DEACTIVATE_CUSTOMER_DOCUMENT: `${PORTS.BLACK_BOX}/api/client/transactionDocument/deactivate`,
    GET_TRANSACTION_BY: `${PORTS.ALPHA + API.ALPHA}/transaction/byId`,
    GET_TRANSACTIONS_COINCIDENCES: `${PORTS.ALPHA +
      API.ALPHA}/transaction/coincidences`,
    GET_EXAMPLE: `${PORTS.ALPHA + API.ALPHA}/ejemplo`,
    PUT_ACCOUNT_CUSTOMER: `${PORTS.BLACK_BOX + API.ALPHA}/customer/`,
    POST_GET_ALL_ACCOUNT: `${PORTS.ALPHA +
      API.ALPHA_CATALOGS}/account/all/combobox`,
    POST_TRANSACTION: `${PORTS.BLACK_BOX + API.ALPHA}/transaction`,
    GET_MESSAGES_BY_ID_LANGUAGE: `${PORTS.ALPHA +
      API.SYSTEM_CONFIGURATION}/messages/byIdLanguage`,
    POST_PASSWORD_RECOVERED_ALPHA: `${PORTS.BLACK_BOX +
      API.API}/Login/PasswordRequest`,
    POST_CHECK_PASSWORD_RECOVERED_ALPHA: `${PORTS.BLACK_BOX +
      API.API}/Login/PasswordRequest/Check`,
    PUT_PASSWORD_RECOVERED_ALPHA: `${PORTS.BLACK_BOX +
      API.API}/Login/PasswordRequest`,
    GET_COUNTRY_CATALOG: `${PORTS.ALPHA +
      API.API}/catalogsClient/masterCountry/all/combobox`,
    GET_NATIONALITIES_CATALOG: `${PORTS.ALPHA +
      API.API}/catalogsClient/masterCountry/nationalities/all/combobox`,
    GET_STATES_CATALOG: `${PORTS.ALPHA +
      API.API}/catalogsClient/state/all/combobox`,
    GET_OCCUPATION_CATALOG: `${PORTS.ALPHA +
      API.API}/CatalogsClient/MasterOccupation/all/ComboBox`,
    POST_GET_FREQUENT_QUESTIONS: `${PORTS.ALPHA +
      API.ALPHA}/reviewTemplate/frequentQuestions`,
    POST_GET_PROFIT_LOSS: `${PORTS.ALPHA + API.ALPHA}/profitLoss`,
    POST_GET_LAST_MOVEMENTS: `${PORTS.ALPHA + API.ALPHA}/lastMovements`,
    POST_GET_DATA_TABLE: `${PORTS.ALPHA + API.ALPHA}/dataTable`,
    GET_DATA_USER: `${PORTS.ALPHA + API.ALPHA}/dc61e3fa/user`,
    POST_USER_BALANCE: `${PORTS.ALPHA + API.ALPHA}/dc61e3fa/user/balance`,
    POST_GET_USER_DEALS: `${PORTS.ALPHA + API.ALPHA}/dc61e3fa/deals/user`,
    POST_GET_DB_DATE: `${PORTS.ALPHA +
      API.SYSTEM_CONFIGURATION}/parameters/dateDataBase
    `,
  },
  PSP: {
    PSPFRAME: `${PSP_DOMAIN}${PORTS.PSP}/Embedded/Index/`,
  },
}; // API_CONSTANTS

export {
  API_CONSTANTS,
  HEADER,
  HEADER_FORM_DATA,
  PORTS,
  PORT,
  API,
  PSP_DOMAIN,
};
