const RECRUITMENT_CONSTANTS = {    
    ACTIONS : {
        SET_RECRUITMENT_INFO_CANDIDATE_FILE : "SET_RECRUITMENT_INFO_CANDIDATE_FILE",
        CLEAR_RECRUITMENT_STATE_STATE : "CLEAR_RECRUITMENT_STATE_STATE",
    },  
};
export { RECRUITMENT_CONSTANTS };