const SYSTEM_CONFIGURATIONS_CONSTANTS = {
  ACTIONS: {
    SET_COMPONENTS_TO_SCREEN: 'SET_COMPONENTS_TO_SCREEN',
    CLEAN_COMPONENTS_TO_SCREEN: 'CLEAN_COMPONENTS_TO_SCREEN',
    SET_FRONT_PARAMETERS: 'SET_FRONT_PARAMETERS',
    SET_DATE_DATABASE: 'SET_DATE_DATABASE',
  },
};
export default SYSTEM_CONFIGURATIONS_CONSTANTS;
