const WORKSTATION_CONSTANTS = {
  SCREEN: {
    ID_SCREEN_CODE: 'SCSALFIL00000000'
  }, //SCREEN
  ACTIONS: {
    CHANGE: 'CHANGE'
  }, //ACTIONS
  MESSAGES_CODES: {}, //MESSAGES_CODES
  COMPONENT: {}, //IDS_COMPONENTS
  EVENTS: {
    SET_TIMEZONES_ARRAY: 'SET_TIMEZONES_ARRAY'
  }
}; //WORKSTATION_CONSTANTS
export { WORKSTATION_CONSTANTS };
